# Generated by Django 5.2.3 on 2025-09-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='text',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
