# Generated by Django 5.2.3 on 2025-09-27 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_mobile_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobile',
            old_name='demo_link',
            new_name='telephone',
        ),
        migrations.RenameField(
            model_name='mobile',
            old_name='username',
            new_name='year',
        ),
    ]
