# Generated by Django 5.2.3 on 2025-10-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0003_rename_demo_link_mobile_telephone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
