# Generated by Django 5.2.3 on 2025-10-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0005_alter_mobile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='image',
            field=models.ImageField(blank=True, upload_to='mobile/images/'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
