# Generated by Django 5.2.7 on 2025-10-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0007_alter_mobile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('telephone', models.CharField(blank=True, max_length=200)),
                ('car_name', models.CharField(blank=True, max_length=200)),
                ('car_color', models.CharField(blank=True, max_length=200)),
                ('car_year', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('telephone', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='created',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='date',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='url',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='year',
        ),
        migrations.AddField(
            model_name='mobile',
            name='color_car',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='mobile',
            name='name_car',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='mobile',
            name='name_user',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='mobile',
            name='telephone_user',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='mobile',
            name='year_car',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
